---

- name: Setting up our VMs
  gather_facts: true
  hosts: ansible-2
  become: yes

  tasks:

    -  name: install docker
       apt:
         update_cache: yes
         pkg:
         - ca-certificates
         - gnupg
         - lsb-release

    -  name: install docker 2
       ansible.builtin.command: 
         cmd: mkdir -p /etc/apt/keyrings
         creates: /etc/apt/keyrings

    -  name: install docker 3
       ansible.builtin.get_url:
         url: https://download.docker.com/linux/ubuntu/gpg
         dest: /etc/apt/keyrings/docker.asc
         mode: '0644'
         force: true

    -  name: install docker 4
       ansible.builtin.apt_repository:
         repo: deb [signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu jammy stable
         state: present

    -  name: install docker 5
       ansible.builtin.shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu  jammy stable"
       args:
         executable: /bin/bash

    #-  name: install docker 6
    #   ansible.builtin.shell: tee /etc/apt/sources.list.d/docker.list > /dev/null
    #   args:
    #     executable: /bin/bash

    -  name: install docker 7
       apt:
         update_cache: yes
         pkg:
         - docker-ce
         - docker-ce-cli
         - containerd.io
         - docker-compose-plugin
    
    - name: Add "user" to group "docker"
      ansible.builtin.user:
        name: user
        groups: docker
        shell: /bin/bash
        comment: "user"
        state: present
      become: yes

    - name: unmask docker
      ansible.builtin.shell: systemctl unmask docker

    - name: start docker  
      ansible.builtin.shell: systemctl start docker

    - name: update
      apt: update_cache=yes
      become: yes 
   
    - name: disable_root_login
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: "PermitRootLogin no"
        state: present
        backup: yes

  handlers:
    - name: restart sshd
      ansible.builtin.service:
        name: = sshd
        state: restarted
